##
# Configuration Schema for Onetime
#
# This YAML file defines the schema for the Onetime Ruby application config
# It uses the Yamale schema validation format (https://github.com/23andMe/Yamale).
#
# Usage:
#
#   1. Define your actual configuration in a separate YAML file (e.g., config.yaml)
#
#   2. Validate your configuration against this schema using Yamale:
#      yamale -s etc/config.schema.yaml etc/config.yaml
#
# Use `any()` with multiple type validators to allow boolean, integer, or
# null/none values. This allows multiple possible types, including the ability
# to specify `none()` for null values. For example, `:default_ttl` and
# `:ttl_options` can now be a boolean, an integer (for `:default_ttl`),
# a list of strings (for `:ttl_options`), or null.
:site: include(':site')
:redis: include(':redis')
:colonels: list(str(), required=True)
:incoming: include(':incoming', required=False)
:emailer: include(':emailer')
:mail: include(':mail')
:locales: list(str())
:services: include(':services')
:limits: include(':limits')
:stathat: include(':stathat', required=False)
:development: include(':development')
:experimental: include(':experimental')

---
:site:
  :host: str()
  :domains: include(':domains')
  :ssl: any()
  :secret: str()
  :authentication: include(':authentication')
  :authenticity: include(':authenticity')
  :plans: include(':plans')
  :support: include(':support')
  :regions: include(':regions')
  :secret_options: include(':secret_options')

:domains:
  :enabled: any()
  :default: str(required=False)
  :cluster:
    :type: str(required=False)
    :api_key: str(required=False)
    :cluster_ip: str(required=False)
    :cluster_host: str(required=False)
    :cluster_name: str()
    :vhost_target: str()

:authentication:
  :enabled: any()
  :signup: any()
  :signin: any()
  :autoverify: any()

:authenticity:
  :type: str()
  :secret_key: str()

:secret_options:
  :default_ttl: any(bool(), int(), str(), null())
  :ttl_options: any(bool(), list(str()), str(), null())

:plans:
  :enabled: any()
  :stripe_key: str(required=False)
  :webook_signing_secret: str(required=False)
  :payment_links: include(':payment_links', required=False)

:payment_links:
  :identity:
    :tierid: str()
    :month: str()
    :year: str()
  :dedication: any()

:support:
  :host: str(required=False)

:regions:
  :enabled: str()
  :current_jurisdiction: str(required=False)
  :jurisdictions: list(include(':jurisdiction'), required=False)

:jurisdiction:
  :identifier: str()
  :display_name: str()
  :domain: str()
  :icon: include(':icon')

:icon:
  :collection: str()
  :name: str()

:incoming:
  :enabled: bool()
  :email: str()
  :passphrase: str()
  :regex: str()

:redis:
  :uri: str()
  :dbs: include(':dbs')
  :config: str(required=False)

:emailer:
  :mode: str()
  :from: str()
  :fromname: str()
  :host: str()
  :port: any()
  :user: any(str(), null())
  :pass: any(str(), null())
  :auth: any(str(), bool())
  :tls: any()

:dbs:
  :session: any(str(), int(), null())
  :splittest: any(str(), int(), null())
  :custom_domain: any(str(), int(), null())
  :customer: any(str(), int(), null())
  :subdomain: any(str(), int(), null())
  :metadata: any(str(), int(), null())
  :email_receipt: any(str(), int(), null())
  :secret: any(str(), int(), null())
  :rate_limit: any(str(), int(), null())
  :feedback: any(str(), int(), null())
  :exception_info: any(str(), int(), null())

:mail:
  :truemail:
    :default_validation_type: str()
    :verifier_email: str()
    :verifier_domain: str(required=False)
    :connection_timeout: int(required=False)
    :response_timeout: int(required=False)
    :connection_attempts: int(required=False)
    :validation_type_for: any(required=False)
    :allowed_domains_only: bool()
    :allowed_emails: list(str(), required=False)
    :blocked_emails: list(str(), required=False)
    :allowed_domains: list(str(), required=False)
    :blocked_domains: list(str(), required=False)
    :blocked_mx_ip_addresses: list(str(), required=False)
    :dns: list(str())
    :smtp_port: int(required=False)
    :smtp_fail_fast: bool()
    :smtp_safe_check: bool()
    :not_rfc_mx_lookup_flow: bool()
    :email_pattern: str(required=False)
    :smtp_error_body_pattern: str(required=False)
    :logger:
      tracking_event: str(required=False)
      stdout: bool(required=False)
      log_absolute_path: str(required=False)

:services:
  :sentry:
    :dsn: str()
    :enabled: any()

:limits:
  :check_status: int()
  :create_secret: int()
  :update_account: int()
  :email_recipient: int()
  :send_feedback: int()
  :authenticate_session: int()
  :get_page: int()
  :dashboard: int()
  :failed_passphrase: int()
  :show_metadata: int()
  :show_secret: int()
  :burn_secret: int()
  :destroy_account: int()
  :forgot_password_request: int()
  :forgot_password_reset: int()
  :update_branding: int()
  :add_domain: int()
  :remove_domain: int()
  :list_domains: int()
  :get_domain: int()
  :verify_domain: int()
  :report_exception: int()
  :generate_apitoken: int()
  :create_account: int()
  :attempt_secret_access: int()

:stathat: any()

:development:
  :enabled: any()
  :debug: any()
  :frontend_host: str()

:experimental:
  :freeze_app: any(str(), bool())
  :csp:
    :enabled: any(str(), bool())
  :markdown:
    :enabled: any(str(), bool())
